// src/common/enums/discrepancy-type.enum.ts

export enum DiscrepancyType {
  INTERNAL_CAPTURED_GATEWAY_FAILED = 'INTERNAL_CAPTURED_GATEWAY_FAILED',
  INTERNAL_PENDING_GATEWAY_SUCCEEDED = 'INTERNAL_PENDING_GATEWAY_SUCCEEDED',
  AMOUNT_MISMATCH = 'AMOUNT_MISMATCH',
  STATUS_MISMATCH = 'STATUS_MISMATCH',
  MISSING_IN_GATEWAY = 'MISSING_IN_GATEWAY',
}
