export enum TransactionState {
  CREATED = 'CREATED',
  ROUTE_SELECTED = 'ROUTE_SELECTED',
  AUTH_INITIATED = 'AUTH_INITIATED',
  AUTHORISED = 'AUTHORISED',
  AUTH_FAILED = 'AUTH_FAILED',
  AUTH_TIMEOUT = 'AUTH_TIMEOUT',
  AUTH_EXPIRED = 'AUTH_EXPIRED',
  CAPTURE_INITIATED = 'CAPTURE_INITIATED',
  CAPTURED = 'CAPTURED',
  PARTIALLY_CAPTURED = 'PARTIALLY_CAPTURED',
  CAPTURE_FAILED = 'CAPTURE_FAILED',
  VOID_INITIATED = 'VOID_INITIATED',
  VOIDED = 'VOIDED',
  REFUND_INITIATED = 'REFUND_INITIATED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  REFUND_FAILED = 'REFUND_FAILED',
  SETTLED = 'SETTLED',
  DISPUTE_OPENED = 'DISPUTE_OPENED',
  DISPUTE_RESOLVED = 'DISPUTE_RESOLVED',
  ABANDONED = 'ABANDONED',
  ROUTE_FAILED = 'ROUTE_FAILED',
  FAILED = 'FAILED',
}

export enum GatewayType {
  STRIPE = 'STRIPE',
  PAYPAL = 'PAYPAL',
  RAZORPAY = 'RAZORPAY',
  PAYTM = 'PAYTM',
  UPI = 'UPI',
  AUTHORIZE_NET = 'AUTHORIZE_NET',
  BRAINTREE = 'BRAINTREE',
  WORLD_PAY = 'WORLD_PAY',
  CHECKOUT_COM = 'CHECKOUT_COM',
  CYBERSOURCE = 'CYBERSOURCE',
  KLARNA = 'KLARNA',
  AFTERPAY = 'AFTERPAY',
  SEZZLE = 'SEZZLE',
  AFFIRM = 'AFFIRM',
  PAYU = 'PAYU',
  NMI = 'NMI',
  BLUEPAY = 'BLUEPAY',
  ELAVON = 'ELAVON',
  FIRST_DATA = 'FIRST_DATA',
}

export enum PaymentMethod {
  CARD = 'CARD',
  UPI = 'UPI',
  NETBANKING = 'NETBANKING',
  WALLET = 'WALLET',
  EMI = 'EMI',
  COD = 'COD',
}

export enum Currency {
  USD = 'USD',
  EUR = 'EUR',
  GBP = 'GBP',
  INR = 'INR',
  AUD = 'AUD',
  CAD = 'CAD',
  JPY = 'JPY',
  CNY = 'CNY',
  BRL = 'BRL',
  ZAR = 'ZAR',
  NGN = 'NGN',
  MXN = 'MXN',
  SGD = 'SGD',
  MYR = 'MYR',
  IDR = 'IDR',
  THB = 'THB',
  VND = 'VND',
  PHP = 'PHP',
  AED = 'AED',
  SAR = 'SAR',
}

export enum CircuitBreakerState {
  CLOSED = 'CLOSED',
  OPEN = 'OPEN',
  HALF_OPEN = 'HALF_OPEN',
}

export enum ReconciliationStatus {
  PENDING = 'PENDING',
  RECONCILED = 'RECONCILED',
  DISCREPANCY = 'DISCREPANCY',
}

export enum WebhookStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  DLQ = 'DLQ',
}

export enum IdempotencyStatus {
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
