export enum PaymentGateway {
  RAZORPAY = 'RAZORPAY',
  STRIPE = 'STRIPE',
  PAYU = 'PAYU',
  UPI = 'UPI',
  PAYSTACK = 'PAYSTACK',
  FLUTTERWAVE = 'FLUTTERWAVE',
  INTERSWITCH = 'INTERSWITCH',
  OPAY = 'OPAY',
}
